backend:
  name: github
  repo: iwat/hugohome
  branch: main

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
